services:
  react_front:
    build:
      context: ./react_front
      dockerfile: Dockerfile.prod
      target: production  
    image: abdel11117/space-explorer:react_front_latest
    ports:
      - "${FRONT_PORT:-5173}:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${API_URL}
    # Pas de volumes en prod (code dans l'image)
    restart: unless-stopped

  react_back_node:
    build:
      context: ./react_back_node
      dockerfile: Dockerfile.prod
      target: production  # Stage de production
    image: abdel11117/space-explorer:react_back_node_latest
    ports:
      - "${BACK_PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${DATA_BASE_PASS}@db:27017/${BDD_NAME}
    volumes:
      - ./react_back_node/image:/app/image  # Seulement les uploads
    restart: unless-stopped

  db:
    image: mongo:latest7.0-alpine
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATA_BASE_PASS}
      - MONGO_INITDB_DATABASE=${BDD_NAME}
    volumes:
      - space-explorer-db-prod:/data/db
    restart: unless-stopped

volumes:
  space-explorer-db-prod: